omma_app_meeting:
    resource: "@OmmaAppBundle/Controller/MeetingController.php"
    type: rest
    name_prefix: omma_app_

omma_app_meeting_agenda:
    resource: "@OmmaAppBundle/Controller/MeetingAgendaController.php"
    type: rest
    name_prefix: omma_app_
    parent: omma_app_meeting

omma_app_meeting_task:
    resource: "@OmmaAppBundle/Controller/MeetingTaskController.php"
    type: rest
    name_prefix: omma_app_
    parent: omma_app_meeting

omma_app_meeting_protocol:
    resource: "@OmmaAppBundle/Controller/MeetingProtocolController.php"
    type: rest
    name_prefix: omma_app_
    parent: omma_app_meeting

omma_app_meeting_file:
    resource: "@OmmaAppBundle/Controller/MeetingFileController.php"
    type: rest
    name_prefix: omma_app_
    parent: omma_app_meeting

omma_app_meeting_attendee:
    resource: "@OmmaAppBundle/Controller/MeetingAttendeeController.php"
    type: rest
    name_prefix: omma_app_
    parent: omma_app_meeting

omma_app_meeting_recurring:
    resource: "@OmmaAppBundle/Controller/MeetingRecurringController.php"
    type: rest
    name_prefix: omma_app
    parent: omma_app_meeting

omma_app_meeting_recurring_exception:
    resource: "@OmmaAppBundle/Controller/MeetingRecurringExceptionController.php"
    type: rest
    name_prefix: omma_app
    parent: omma_app_meeting_recurring
