services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    security.access.post_voter:
        class: Omma\AppBundle\Voter\MeetingVoter
        public: false
        tags:
            - { name: security.voter }
        arguments:
            - @omma.app.manager.attendee

    omma.app.request.listener.locale:
        class: Omma\AppBundle\EventListener\Request\LocaleListener
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - %omma.languages%

    omma.app.form.type.rest_base:
        class: Omma\AppBundle\Form\Type\RestBaseForm
        tags:
            - { name: form.type, alias: omma_rest_base }

    omma.app.form.type.meeting_agenda:
        class: Omma\AppBundle\Form\Type\MeetingAgendaForm
        tags:
            - { name: form.type, alias: omma_meeting_agenda }

    omma.app.form.type.meeting_agenda_collection:
        class: Omma\AppBundle\Form\Type\MeetingAgendaCollectionForm
        tags:
            - { name: form.type, alias: omma_meeting_agenda_collection }

    omma.app.mail.abstract:
        class: Omma\AppBundle\Mail\AbstractMailer
        public: false
        arguments:
            - @swiftmailer.mailer
            - @router
            - @twig
            - %omma.mail.from%

    omma.app.mail.invitation:
        class: Omma\AppBundle\Mail\InvitationMailer
        arguments:
            - @omma.app.mail.abstract
            - @omma.app.manager.attendee

    omma.app.twig.extension.meeting:
        class: Omma\AppBundle\Twig\MeetingTwigExtension
        tags:
            - { name: twig.extension }
        arguments:
            - @omma.app.manager.meeting
            - @security.token_storage

    omma.app.twig.extension.task:
        class: Omma\AppBundle\Twig\TaskTwigExtension
        tags:
            - { name: twig.extension }
        arguments:
            - @omma.app.manager.task
            - @security.token_storage

