omma_meeting:
    resource: "@OmmaMeetingBundle/Controller/"
    type: annotation
    prefix:   /

omma_user:
    resource: "@OmmaUserBundle/Controller/"
    type:     annotation
    prefix:   /

omma_app:
    resource: "@OmmaAppBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
