<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Application\Sonata\UserBundle\Entity;

use Omma\UserBundle\Entity\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 * working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @ORM\Entity()
 * @ORM\Table(name="fos_user_user")
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{

    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     *
     * @var integer $id
     */
    protected $id;

    /**
     *
     * @var \Omma\AppBundle\Entity\Meeting @ORM\ManyToMany(targetEntity="\Omma\AppBundle\Entity\Meeting", mappedBy="users", orphanRemoval=true)
     */
    protected $meetings;

    /**
     *
     * @var \Omma\AppBundle\Entity\Task @ORM\OneToMany(targetEntity="\Omma\AppBundle\Entity\Task", mappedBy="user", orphanRemoval=true)
     */
    protected $tasks;

    /**
     * Constructor
     */
    public function __construct()
    {
        parent::__construct();
        $this->meetings = new \Doctrine\Common\Collections\ArrayCollection();
        $this->tasks = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Add meetings
     *
     * @param \Omma\AppBundle\Entity\Meeting $meetings            
     * @return User
     */
    public function addMeeting(\Omma\AppBundle\Entity\Meeting $meetings)
    {
        $this->meetings[] = $meetings;
        
        return $this;
    }

    /**
     * Remove meetings
     *
     * @param \Omma\AppBundle\Entity\Meeting $meetings            
     */
    public function removeMeeting(\Omma\AppBundle\Entity\Meeting $meetings)
    {
        $this->meetings->removeElement($meetings);
    }

    /**
     * Get meetings
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMeetings()
    {
        return $this->meetings;
    }

    /**
     * Add tasks
     *
     * @param \Omma\AppBundle\Entity\Task $tasks            
     * @return User
     */
    public function addTask(\Omma\AppBundle\Entity\Task $tasks)
    {
        $this->tasks[] = $tasks;
        
        return $this;
    }

    /**
     * Remove tasks
     *
     * @param \Omma\AppBundle\Entity\Task $tasks            
     */
    public function removeTask(\Omma\AppBundle\Entity\Task $tasks)
    {
        $this->tasks->removeElement($tasks);
    }

    /**
     * Get tasks
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTasks()
    {
        return $this->tasks;
    }
}
