Omma\AppBundle\Entity\MeetingRecurring:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        meeting:
            expose: true
        dateStart:
            expose: true
        dateEnd:
            expose: true
        type:
            expose: true
        recurring:
            expose: true
