Omma\AppBundle\Entity\Protocol:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        meeting:
            expose: true
        text:
            expose: true
        final:
            expose: true
