Omma\AppBundle\Entity\Agenda:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        name:
            expose: true
        sortingOrder:
            expose: true
        children:
            expose: true
