Omma\AppBundle\Entity\Meeting:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        name:
            expose: true
        dateStart:
            expose: true
        dateEnd:
            expose: true
        prev:
            expose: true
            max_depth: 1
        next:
            expose: true
            max_depth: 1
